// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5bqZ6eLjFe95eSAcUsWCkhfyNKMusSTw',
    appId: '1:393183177917:web:b8c6db0e5b76387bec5bd4',
    messagingSenderId: '393183177917',
    projectId: 'currencrconverterapp',
    authDomain: 'currencrconverterapp.firebaseapp.com',
    storageBucket: 'currencrconverterapp.firebasestorage.app',
    measurementId: 'G-JZJLK70CK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKP8KD8Nq11vWxjlR6aVaKdFm8qg4K9E',
    appId: '1:393183177917:android:2e3eab45fecefff0ec5bd4',
    messagingSenderId: '393183177917',
    projectId: 'currencrconverterapp',
    storageBucket: 'currencrconverterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXLiqYeCq4LJpoZsAo5RiLT2O0A2hfcA',
    appId: '1:393183177917:ios:74e6ec66341ae884ec5bd4',
    messagingSenderId: '393183177917',
    projectId: 'currencrconverterapp',
    storageBucket: 'currencrconverterapp.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXLiqYeCq4LJpoZsAo5RiLT2O0A2hfcA',
    appId: '1:393183177917:ios:74e6ec66341ae884ec5bd4',
    messagingSenderId: '393183177917',
    projectId: 'currencrconverterapp',
    storageBucket: 'currencrconverterapp.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5bqZ6eLjFe95eSAcUsWCkhfyNKMusSTw',
    appId: '1:393183177917:web:8e0518c1c3f498a4ec5bd4',
    messagingSenderId: '393183177917',
    projectId: 'currencrconverterapp',
    authDomain: 'currencrconverterapp.firebaseapp.com',
    storageBucket: 'currencrconverterapp.firebasestorage.app',
    measurementId: 'G-1PK47H92QK',
  );
}
